name: Detect Secrets

on:
  push:

jobs:
  detect-secrets:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: detect-secrets
        uses: sensyn-robotics/github-action-detect-secrets@v1
        with:
          baseline: '.secrets.baseline.json'
          detect-secrets-version: '1.5.0'
